#!/bin/bash
# gets a fresh Pharo image and loads Mapless

echo "Downloading fresh Pharo image and a VM ..."

wget -O- get.pharo.org/30+vm | bash

echo "Opening Pharo to load Mapless ..."
./pharo-ui Pharo.image MaplessBuilder.st

echo "Ready!"
