#!/bin/bash
#
# Cleans up libraries and modules that can be installed from remote sources and
# local files that can be rebuilt from sources

rm -rf pharo
rm -rf pharo-ui
rm -rf *.log
rm -rf pharo-vm
rm -rf package-cache